apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-jenkins
spec:
  selector:
    matchLabels:
      app: myapp-jenkins
  template:
    metadata:
      labels:
        app: myapp-jenkins
    spec:
      containers:
      - name: myapp-jenkins
        image: docker.io/pragnesh9789/jenkins-img:latest
        ports:
        - containerPort: 80
